'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasReportado

    '''<summary>
    '''GraficoMasReportado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GraficoMasReportado As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''GridViewMasReportado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewMasReportado As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceMasReportado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceMasReportado As Global.System.Web.UI.WebControls.SqlDataSource
End Class
