'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasVisto

    '''<summary>
    '''LinkButtonInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonInicio As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkButtonFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonFin As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''CalendarInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarInicio As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''CalendarFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarFin As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''GraficoMasVisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GraficoMasVisto As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''GridViewVMasVisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewVMasVisto As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSourceMasVisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceMasVisto As Global.System.Web.UI.WebControls.SqlDataSource
End Class
