'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UsuariosTops

    '''<summary>
    '''GraficoUsuariosTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GraficoUsuariosTop As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''SqlDataSourceUsuariosTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceUsuariosTop As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''GridViewUsuariosTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewUsuariosTop As Global.System.Web.UI.WebControls.GridView
End Class
